
name: gruppenname-frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  TEST-FE:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:unit

  PUBLISH-FE:
    runs-on: self-hosted
    needs: TEST-FE

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: registry.datexis.com/ksachs/gruppenname-frontend:latest
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSPHRASE }}
          registry: registry.datexis.com
          snapshot: true
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Restart gruppenname-frontend pod
        run: kubectl -n sachs delete pod -l app=gruppenname-frontend

